I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 89, in script call
    call interroger
  File "game/scripts/interrogatoire.rpy", line 38, in script call
    call dialogue_eloise
  File "game/scripts/dialogues.rpy", line 65, in script
    $ end_dialogue("eloise")
  File "game/scripts/dialogues.rpy", line 65, in <module>
    $ end_dialogue("eloise")
  File "game/scripts/dialogues.rpy", line 41, in end_dialogue
    renpy.with_statement(dissolve, _transition_time=0.2)
TypeError: with_statement() got an unexpected keyword argument '_transition_time'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 89, in script call
    call interroger
  File "game/scripts/interrogatoire.rpy", line 38, in script call
    call dialogue_eloise
  File "game/scripts/dialogues.rpy", line 65, in script
    $ end_dialogue("eloise")
  File "D:\renpy-8.3.3\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8.3.3\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/dialogues.rpy", line 65, in <module>
    $ end_dialogue("eloise")
  File "game/scripts/dialogues.rpy", line 41, in end_dialogue
    renpy.with_statement(dissolve, _transition_time=0.2)
TypeError: with_statement() got an unexpected keyword argument '_transition_time'

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Meurtre au Manoir 1.0
Tue Apr  1 11:58:37 2025
