I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 40, in script call
    call interroger
  File "game/script.rpy", line 40, in script call
    call interroger
  File "game/script.rpy", line 37, in script call
    call inspecter_scene_meurtre
  File "game/script.rpy", line 40, in script call
    call interroger
  File "game/scripts/interrogatoire.rpy", line 54, in script call
    call dialogue_victor
  File "game/scripts/dialogues.rpy", line 55, in script
    show victor neutral
Exception: Image 'victor' does not accept attributes 'neutral'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 40, in script call
    call interroger
  File "game/script.rpy", line 40, in script call
    call interroger
  File "game/script.rpy", line 37, in script call
    call inspecter_scene_meurtre
  File "game/script.rpy", line 40, in script call
    call interroger
  File "game/scripts/interrogatoire.rpy", line 54, in script call
    call dialogue_victor
  File "game/scripts/dialogues.rpy", line 55, in script
    show victor neutral
  File "D:\renpy-8.3.3\renpy\ast.py", line 1124, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\renpy-8.3.3\renpy\ast.py", line 1087, in show_imspec
    renpy.config.show(name,
  File "D:\renpy-8.3.3\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\renpy-8.3.3\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "D:\renpy-8.3.3\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "D:\renpy-8.3.3\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'victor' does not accept attributes 'neutral'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Meurtre au Manoir 1.0
Tue Apr  1 09:26:07 2025
